### ISSUE TITLE
RuntimeError occurs when training

### ISSUE THREAD

**Issue by xuanhan863** [b04901014/FG-transformer-TTS#2]
Hi, really nice work. 

I tried to use "wav2vec2-large-xlsr-53" as encoder, then made a pretreatment.

but, It appeared during training
     RuntimeError: mat1 and mat2 shapes cannot be multiplied

I wanna know if I can change the WAV2VEC2 encoder? 
thank you.

**Comment by b04901014** [comment]
I believe the large version of wav2vec 2.0 has 1024 hidden units. Therefore the the `--emo_embed_dim` should be changed to 1024. Hope that works.

**Comment by xuanhan863** [comment]
thanks for the reply : )
It seems that this may be a problem.  I will continue to experiment and explore.

**Comment by xuanhan863** [comment]
3 speakers, 20,000 data, training to 380 epoch.
I don't know where to happen, all loss has become nan.0
loss=nan, loss_step=nan.0, rec_loss_step=nan.0, gate_loss_step=nan.0, guided_loss_step=nan.0
--batch_size 16
--val_split 0.8
--check_val_every_n_epoch 30
--use_guided_attn
--training_step 500000
--n_guided_steps 500000
