### ISSUE TITLE
About Style embedding

### ISSUE THREAD

**Issue by guoaoo** [b04901014/FG-transformer-TTS#3]
Hi @b04901014 , thanks for your great implementation!

I have a question about code and paper. In the **Style embedding** section of the paper

> Similarly, the output features from wav2vec 2.0 are also processed by a LSTM for fine-grained style embeddings. However, instead of taking the mean across the time dimension, we adopt average pooling with stride 4 and kernel size 8 to smooth out the representation. **Based on this representation**, each time steps will be fed as a query to a multi-head attention with another trainable codebook as key and value to produce a sequence of style embeddings

I think the output of LSTM should be pooled on average before going to MHA, but in the code the order is reversed
https://github.com/b04901014/FG-transformer-TTS/blob/d0362cc8530ebe0744ad3104bf1da8145f5b1aec/ETTS/ettstransformer.py#L68-L73

**Comment by b04901014** [comment]
Hi. Much thanks for finding this out! The code implementation is what we intended, so it's a mistake on the paper. I cannot guarantee what will happen if the order is reversed, but I doubt the performance will differ much. I'll update the arXiv paper accordingly.

**Comment by guoaoo** [comment]
Thanks for your quick reply.
